In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3])
A * 2

array([2, 4, 6])

In [3]:
np.random.seed(2)

In [4]:
m, n = 4, 3
A = np.random.randint(0, 10, m*n).reshape(m,n)
b = np.random.randint(0, 10, n)

In [5]:
A

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5]])

In [6]:
b

array([7, 3, 6])

In [7]:
A * b

array([[56, 24, 36],
       [14, 24, 42],
       [14,  3, 30],
       [28, 12, 30]])

In [13]:
np.random.seed(3)

In [14]:
b = np.random.randint(0, 10, n+1)
b

array([8, 9, 3, 8])

In [22]:
C = A * b[:, np.newaxis]
C

array([[64, 64, 48],
       [18, 72, 63],
       [ 6,  3, 15],
       [32, 32, 40]])

In [24]:
b

array([8, 9, 3, 8])

In [28]:
b[:, np.newaxis]

array([[8],
       [9],
       [3],
       [8]])

In [31]:
b[np.newaxis ,:]

array([[8, 9, 3, 8]])

In [51]:
np.random.seed(11)

In [54]:
m, n = 4, 3
a = np.random.randint(0, 10, m).reshape(-1, 1)
b = np.random.randint(0, 10, n)
c = b.reshape(-1, 3)

In [55]:
a, b, c

(array([[8],
        [0],
        [0],
        [4]]),
 array([2, 1, 5]),
 array([[2, 1, 5]]))

In [56]:
a*b

array([[16,  8, 40],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 8,  4, 20]])

In [58]:
a*c

array([[16,  8, 40],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 8,  4, 20]])

In [61]:
a.shape, b.shape, c.shape

((4, 1), (3,), (1, 3))

In [62]:
np.random.seed(10)

In [78]:
A = np.random.randint(0,9,12).reshape(4,3)
b = np.random.randint(0,9,3).reshape(3,1)
A, A.shape, A[:, 0], b 

(array([[8, 1, 2],
        [8, 5, 0],
        [2, 7, 3],
        [0, 4, 2]]),
 (4, 3),
 array([8, 8, 2, 0]),
 array([[0],
        [3],
        [3]]))

In [71]:
C = np.dot(A, b)
C_ = np.array([A[:, [j]] * b[j] for j in range(A.shape[1])])

In [72]:
C

array([[24],
       [70],
       [96],
       [34]])

In [73]:
C_

array([[[16],
        [ 0],
        [ 0],
        [16]],

       [[ 0],
        [ 6],
        [48],
        [18]],

       [[ 8],
        [64],
        [48],
        [ 0]]])

In [74]:
C_.sum(axis=0)

array([[24],
       [70],
       [96],
       [34]])