In [1]:
import numpy as np

In [4]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [5]:
B = np.array([[10,20],[30,40]])
B

array([[10, 20],
       [30, 40]])

In [7]:
A+B

array([[11, 22],
       [33, 44]])

In [9]:
# ik * kj = ij
# 2,3 * 3,2 = 2,2
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[2,1],[1,2],[1,1]])
np.dot(A,B)

array([[ 7,  8],
       [19, 20]])

In [10]:
A = np.matrix([[1,2,3],[4,5,6]])
B = np.matrix([[2,1],[1,2],[1,1]])
A*B

matrix([[ 7,  8],
        [19, 20]])

In [16]:
# transpose

A = np.arange(1,7).reshape(2,3)
print(A)
A.transpose(1,0)

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
# unit maxtrix / identity matrix

A = np.matrix([[2,4],[4,2]])
I = np.matrix(np.eye(2))

In [20]:
A, I

(matrix([[2, 4],
         [4, 2]]),
 matrix([[1., 0.],
         [0., 1.]]))

In [21]:
print(A*I)
print(I*A)

[[2. 4.]
 [4. 2.]]
[[2. 4.]
 [4. 2.]]


In [ ]:
# inverse matrix