### Operations

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
B = np.array([[10,20],[30,40]])
B

array([[10, 20],
       [30, 40]])

In [4]:
A+B

array([[11, 22],
       [33, 44]])

In [5]:
# ik * kj = ij
# 2,3 * 3,2 = 2,2
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[2,1],[1,2],[1,1]])
np.dot(A,B)

array([[ 7,  8],
       [19, 20]])

In [6]:
A = np.matrix([[1,2,3],[4,5,6]])
B = np.matrix([[2,1],[1,2],[1,1]])
A*B

matrix([[ 7,  8],
        [19, 20]])

In [7]:
# transpose

A = np.arange(1,7).reshape(2,3)
print(A)
A.transpose(1,0)

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
# unit maxtrix / identity matrix

A = np.matrix([[2,4],[4,2]])
I = np.matrix(np.eye(2))

In [10]:
A, I

(matrix([[2, 4],
         [4, 2]]),
 matrix([[1., 0.],
         [0., 1.]]))

In [11]:
print(A*I)
print(I*A)

[[2. 4.]
 [4. 2.]]
[[2. 4.]
 [4. 2.]]


In [12]:
# inverse matrix
# singular matrix 역행렬이 없음
# non-singular matrix 역행렬이 있음

In [13]:
# 역행렬을 이용하면 선형 연립방정식을 쉽게 풀 수 있다.
A = np.matrix([[2,1],[-6,3]])
b = np.matrix([[3],[-27]])

In [14]:
A.I * b

matrix([[ 3.],
        [-3.]])

In [15]:
# diagonal matrix

D = np.matrix(np.eye(3)*np.array([2,1,4]))
print(D)
print(D.I)
print(D * D.I)

[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 4.]]
[[0.5  0.   0.  ]
 [0.   1.   0.  ]
 [0.   0.   0.25]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
np.eye(3)*np.array([3,2,5])

array([[3., 0., 0.],
       [0., 2., 0.],
       [0., 0., 5.]])

In [17]:
# symmetric matrix
# diagonalization

A = np.matrix([[2,4],[4,2]])
A, A.T

(matrix([[2, 4],
         [4, 2]]),
 matrix([[2, 4],
         [4, 2]]))

In [18]:
X = np.matrix([[0.7071, -0.7071],[0.7071,0.7071]])
A, X

(matrix([[2, 4],
         [4, 2]]),
 matrix([[ 0.7071, -0.7071],
         [ 0.7071,  0.7071]]))

In [19]:
D = X.I * A * X
D

matrix([[ 6.,  0.],
        [ 0., -2.]])

In [20]:
# 대각화가 모든 행렬에 대해 가능한 것은 아님
# 하지만 대칭행렬은 어떤 경우라도 대각화가 가능
# 이 사실로부터 임의의 모든 행렬은 특잇값 분해가 가능하다는 것을 보일 수 있다.
# singular value decomposition