### Transpose

In [2]:
import numpy as np

In [3]:
A = np.arange(1,13).reshape(2,2,-1)
A

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [4]:
A.T

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [5]:
A.transpose(1,2,0)

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [6]:
A = np.array([[1.,2.],[3.,4.],[5.,6.]])


In [7]:
array = np.arange(1,1001).reshape(2,5,100)

In [8]:
array1 = array.reshape(1,1000)
array1

array([[   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
          12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
          23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
          34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
          45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
          56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
          67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
          78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
          89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
         100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
         111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
         122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
         133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
         144,  145,  146,  147,  148, 

In [9]:
array1.reshape(4, 5, 50)

array([[[   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
           11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
           21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
           31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
           41,   42,   43,   44,   45,   46,   47,   48,   49,   50],
        [  51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
           61,   62,   63,   64,   65,   66,   67,   68,   69,   70,
           71,   72,   73,   74,   75,   76,   77,   78,   79,   80,
           81,   82,   83,   84,   85,   86,   87,   88,   89,   90,
           91,   92,   93,   94,   95,   96,   97,   98,   99,  100],
        [ 101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
          111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
          121,  122,  123,  124,  125,  126,  127,  128,  129,  130,
          131,  132,  133,  134,  135,  136,  137,  138,  139,  140,
          141,  142,  143,  144,

In [10]:
a = np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [11]:
a.shape

(3, 3, 3)

In [12]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [15]:
print('0,1,2')
print(a.transpose(0,1,2))
print('\n1,2,0')
print(a.transpose(1,0,2))
print('\n2,1,0')
print(a.transpose(2,0,1))

0,1,2
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

1,2,0
[[[ 1  2  3]
  [10 11 12]
  [19 20 21]]

 [[ 4  5  6]
  [13 14 15]
  [22 23 24]]

 [[ 7  8  9]
  [16 17 18]
  [25 26 27]]]

2,1,0
[[[ 1  4  7]
  [10 13 16]
  [19 22 25]]

 [[ 2  5  8]
  [11 14 17]
  [20 23 26]]

 [[ 3  6  9]
  [12 15 18]
  [21 24 27]]]
